### ISSUE TITLE
ESP32 Arduino Example

### ISSUE THREAD

**Issue by nfernandezsanz** [stm32duino/VL53L1X#12]
Hi, I am triying to use this library with an ESP32. Could you please attach a basic example to me? My final goal is to replicate the example of the people counter created by ST, do you see it possible?
Thanks.

**Comment by cparata** [comment]
Hi @NFS-4920 ,
yes I think it is possible. Actually I already ported the people counting demo [here](https://github.com/stm32duino/X-NUCLEO-53L1A1/blob/master/examples/X_NUCLEO_53L1A1_People_Counting/X_NUCLEO_53L1A1_People_Counting.ino) for the X-NUCLEO-53L1A1 expansion board based on the same component. It should be easy to adapt it for the single component. You just need to remove the references to the right and left satellites and replace the initialization of the top sensor with your hardware setup. It means replacing these lines of code:

```
// Create VL53L1X top component.
xshutdown_top = new STMPE1600DigiOut(&DEV_I2C, GPIO_15, (0x42 * 2));
sensor_vl53l1_top = new VL53L1_X_NUCLEO_53L1A1(&DEV_I2C, xshutdown_top, A2);
```

with

```
// Create VL53L1X top component.
sensor_vl53l1_top = new VL53L1X(&DEV_I2C, XSHUT_PIN, GPIO1_PIN);
```

where XSHUT_PIN is the SHUTDOWN pin in your setup and GPIO1_PIN is the GPIO1 pin in your setup.
You also need to replace these includes:

```
#include <vl53l1x_x_nucleo_53l1a1_class.h>
#include <stmpe1600_class.h>
```

with

```
#include <vl53l1x_class.h>
```

The rest should be fine as it is also with your hardware setup.
Best Regards,
Carlo

**Comment by nfernandezsanz** [comment]
Hi @cparata,
It worked! 
As you said I removed the references to the right and left satellites. In addition, I modified this line:
`VL53L1_X_NUCLEO_53L1A1 *sensor_vl53l1_top;`
with
`VL53L1X *sensor_vl53l1_top;`
I think the code can be useful to other people. Tell me if it is correct to upload all the code to this thread (I have removed some lines that I consider not necessary for the ESP32 with this setup). 
Thank you very much for the reference and excellent work.

**Comment by cparata** [comment]
Hi @NFS-4920 ,
I'm glad that you were able to use the library! Any contribution is welcome to improve the library. So, I'm open to add the example into the library and the best way is that you submit a Pull Request on the github repository. The important thing is to describe well the hardware setup, so a user can easily reproduce it. Please give a look at the beginning of [this sketch](https://github.com/stm32duino/VL53L1/blob/master/examples/VL53L1_Sat_HelloWorld/VL53L1_Sat_HelloWorld.ino) where it is well explained how to connect with wires all the pins of the sensor board and mother board. What is the VL53L1X board that you are using in your setup?
Thanks in advance and best regards,
Carlo
